### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by diegomora02** [boy1dr/HDD_DJ_controller#1]
Could you please add the schematics for the project? The 3 seconds from the video weren't enough to copy, maybe on a program like fritzing? Thanks in advance

**Comment by boy1dr** [comment]
![hdd_motor-4wite](https://user-images.githubusercontent.com/5217188/30463325-55807fe6-9a0e-11e7-8c0a-10aea999c39f.png)
The HDD motor is comprised of 3 coils, the connector exposes the 3 coils and a common like in the image.

So if you connect those 4 wires directly to your Arduino you can sense the voltage rise. 
There was no additional circuitry needed for simple operation.

If you turn the plater too slowly it won't make enough voltage to sense but you could use a quad channel OP-Amp to boost the signal but i guess that adds complexity to it.
